---
# Load containers presets

- block:
    - name: Search container presets
      find:
        paths: "{{ role_path }}/defaults/containers"
        patterns: "*.yml"
      register: docker_presets_search_containers_result
      delegate_to: localhost

    - name: Load container presets
      include_vars:
        file: "{{ file.path }}"
        name: docker_presets_container
      loop: "{{ docker_presets_search_containers_result.files }}"
      loop_control:
        label: "{{ file.path | basename }}"
        loop_var: file
      register: docker_presets_load_containers_result
      delegate_to: localhost

    # The to_json | from_json trick here is a workaround to bug
    # https://github.com/ansible/ansible/issues/20379

    - name: Setup fact with containers presets
      set_fact:
        docker_presets_containers: >-
          {{ docker_presets_load_containers_result.results
             | map(attribute="ansible_facts.docker_presets_container")
             | list
             | to_json
             | from_json
             | json_query(docker_presets_containers_json_query) }}
  tags:
    - role::docker_presets
    - role::docker_presets::containers
