---
# Load images presets

- block:
    - name: setup fact with image build path
      set_fact:
        docker_presets_build_path: "{{ role_path }}/files"

    - name: search image presets
      find:
        paths: "{{ role_path }}/defaults/images"
        patterns: "*.yml"
      register: docker_presets_search_images_result

    - name: load image presets
      include_vars:
        file: "{{ file.path }}"
        name: docker_presets_image
      with_items: "{{ docker_presets_search_images_result.files }}"
      loop_control:
        label: "{{ file.path }}"
        loop_var: file
      register: docker_presets_load_images_result

    - name: setup fact with images presets
      set_fact:
        docker_presets_images: >-
          {{ images | map("combine", extra_buildargs, recursive=true) | list }}
      vars:
        extra_buildargs:
          path: "{{ docker_presets_build_path }}"
          buildargs:
            user: "{{ docker_presets_user }}"
            password: "{{ docker_presets_password }}"

        images: >-
          {{ docker_presets_load_images_result.results
             | map(attribute="ansible_facts.docker_presets_image")
             | list }}
  tags:
    - role::docker_presets
    - role::docker_presets::images
