---
# Load images presets

- block:
    - name: search image presets
      local_action:
        module: find
        paths: "{{ role_path }}/defaults/images"
        patterns: "*.yml"
      register: docker_presets_search_images_result

    - name: load image presets
      local_action:
        module: include_vars
        file: "{{ file.path }}"
        name: docker_presets_image
      loop: "{{ docker_presets_search_images_result.files }}"
      loop_control:
        label: "{{ file.path | basename }}"
        loop_var: file
      register: docker_presets_load_images_result

    # The to_json | from_json trick here is a workaround to bug
    # https://github.com/ansible/ansible/issues/20379

    - name: setup fact with images presets
      set_fact:
        docker_presets_images: >-
          {{ images
             | map("combine", extra_buildargs, recursive=true)
             | map("combine", extra_buildargs, recursive=true)
             | map("combine", http_proxy_buildargs, recursive=true)
             | map("combine", https_proxy_buildargs, recursive=true)
             | map("combine", no_proxy_buildargs, recursive=true)
             | list
             | docker_presets_add_attributes(default_path, overwrite=false)
             | to_json
             | from_json
             | json_query(docker_presets_images_json_query) }}
      vars:
        images: >-
          {{ docker_presets_load_images_result.results
             | map(attribute="ansible_facts.docker_presets_image")
             | list }}

        default_path:
          path: "{{ docker_presets_build_path }}"

        http_proxy_buildargs: >-
          {{ (ansible_facts.env.http_proxy | default('') | length > 0)
             | ternary(
                 { "buildargs": { "http_proxy": ansible_facts.env.http_proxy }},
                 {}) }}

        https_proxy_buildargs: >-
          {{ (ansible_facts.env.https_proxy | default('') | length > 0)
             | ternary(
                 { "buildargs": {
                      "https_proxy": ansible_facts.env.https_proxy }},
                 {}) }}

        no_proxy_buildargs: >-
          {{ (ansible_facts.env.no_proxy | default('') | length > 0)
             | ternary(
                 { "buildargs": { "no_proxy": ansible_facts.env.no_proxy }},
                 {}) }}

        extra_buildargs:
          buildargs:
            user: "{{ docker_presets_user }}"
            password: "{{ docker_presets_password }}"

    - name: setup directory for dockerfiles
      file:
        path: "{{ docker_presets_build_path }}"
        state: directory
        mode: 0700

    - name: setup dockerfiles
      copy:
        src: "files/{{ item.dockerfile }}"
        dest: "{{ docker_presets_build_path }}/{{ item.dockerfile }}"
        mode: 0600
      loop: "{{ docker_presets_images }}"
      loop_control:
        label: "{{ docker_presets_build_path }}/{{ item.dockerfile }}"
  tags:
    - role::docker_presets
    - role::docker_presets::images
