---
# Role tasks

- name: Configure images presets
  include_tasks: images.yml
  tags:
    - role::docker_presets
    - role::docker_presets::images

- name: Configure containers presets
  include_tasks: containers.yml
  tags:
    - role::docker_presets
    - role::docker_presets::containers
