---
# Role tasks

- name: configure images presets
  include: images.yml
  static: false
  tags:
    - role::docker_presets
    - role::docker_presets::images

- name: configure containers presets
  include: containers.yml
  static: false
  tags:
    - role::docker_presets
    - role::docker_presets::containers
