---

- name: Converge
  hosts: molecule_hosts
  gather_facts: no
  roles:
    - amtega.docker_presets
  tasks:
    - name: Test dynamic load of images presets
      assert:
        that:
          - docker_presets_images | length > 0

          - docker_presets_images
            | selectattr('name', 'equalto', 'centos-6') | list | length > 0

          - docker_presets_images
            | selectattr('name', 'equalto', 'centos-7') | list | length > 0

          - docker_presets_images
            | selectattr('name', 'equalto', 'fedora-29') | list | length > 0

          - docker_presets_images
            | selectattr('name', 'equalto', 'fedora-30') | list | length > 0

          - docker_presets_images
            | selectattr('name', 'equalto', 'fedora-31') | list | length > 0

    - name: Test dynamic load of containers presets
      assert:
        that:
          - docker_presets_containers | length > 0

          - docker_presets_containers
            | selectattr('name', 'equalto', 'centos-6') | list | length > 0

          - docker_presets_containers
            | selectattr('name', 'equalto', 'centos-7') | list | length > 0

          - docker_presets_containers
            | selectattr('name', 'equalto', 'fedora-29') | list | length > 0

          - docker_presets_containers
            | selectattr('name', 'equalto', 'fedora-30') | list | length > 0

          - docker_presets_containers
            | selectattr('name', 'equalto', 'fedora-31') | list | length > 0

    - name: Test docker_presets_add_attributes filter
      assert:
        that:
          - "docker_presets_images
             | docker_presets_add_attributes({'new_attribute': 'hello world'})
             | selectattr('new_attribute', 'equalto', 'hello world')
             | list | length > 0"

          - "docker_presets_containers
             | docker_presets_add_attributes({'new_attribute': 'hello world'})
             | selectattr('new_attribute', 'equalto', 'hello world')
             | list | length > 0"

    - name: Test docker_presets_randomize_names filter
      assert:
        that:
          - docker_presets_images
            | docker_presets_randomize_names
            | selectattr('name', 'equalto', 'centos-7') | list | length == 0

          - docker_presets_containers
            | docker_presets_randomize_names
            | selectattr('name', 'equalto', 'centos-7') | list | length == 0

    - name: Test docker_presets_remove_attributes filter
      assert:
        that:
          - "'new_attribute'
             not in docker_presets_images
                    | docker_presets_add_attributes(
                        {'new_attribute': 'hello world'})
                    | docker_presets_remove_attributes(['new_attribute'])"

          - "'new_attribute'
             not in docker_presets_containers
                    | docker_presets_add_attributes(
                        {'new_attribute': 'hello world'})
                    | docker_presets_remove_attributes(['new_attribute'])"

    - name: Test docker_presets_repeat filter
      assert:
        that:
          - docker_presets_images
            | docker_presets_repeat(3)
            | length == docker_presets_images | length * 3

          - docker_presets_containers
            | docker_presets_repeat(3)
            | length == docker_presets_containers | length * 3
